### ISSUE TITLE
toxic no longer plays sounds defined in the conf

### ISSUE THREAD

**Issue by ElLamparto** [JFreegman/toxic#354]
I have the last version from Debian repo (the problem appeared a few updates before).
OS: Debian Jessie.

**Comment by JFreegman** [comment]
The binary is currently incomplete. Working on it.

**Comment by ElLamparto** [comment]
Thak you, Good luck!

**Comment by JFreegman** [comment]
Sounds should be working now for both the deb and rpm packaged 64-bit versions (though it might take a day for the repo to update)

**Comment by ElLamparto** [comment]
It still doesn't work for 32bit. I noticed that the last exetutable where the sounds worked, is 1/3 bigger than the current one.

**Comment by JFreegman** [comment]
Are you sure the 32-bit version doesn't work? It should, although it took a couple extra days to get it working. Could check again with the latest build just to be sure? I'm having trouble with my 32-bit VM.

I'm not sure what you're talking about regarding the binary sizes. The most recent binary is 2.25MB (https://build.tox.chat/job/toxic_build_linux_x86-64_release/) and the binary before the sound lib was linked was 2.23MB (https://build.tox.chat/job/toxic_build_linux_x86-64_release/72/)

**Comment by ElLamparto** [comment]
Binaries (Debian):
New (sounds NOK): -rwxr-xr-x 1 root root 3837612 Oct 24 02:35 toxic
Old (sounds OK):     -rwxr-xr-x 1 root root 5303068 Sep  6 12:56 toxic

I shall retest it in the weekend.

**Comment by ElLamparto** [comment]
It is unstable. Sometimes it plays sounds, most often it doesn't. This ticket should be reopened.

**Comment by JFreegman** [comment]
Can you elaborate? What do you mean by sometimes? Different installs? Different machines? Randomly with no changing variables?

**Comment by JFreegman** [comment]
There was a problem with the 32-bit package that I just fixed. You can [test it](https://build.tox.chat/job/toxic_pkg_linux_deb_x86_nightly_release/40/artifact/toxic-0.6.1-40.deb) if you want, or wait 24h for the repo to update.

64-bit package looks fine.

**Comment by ElLamparto** [comment]
Same machine. I shall test the new version in the coming weekend and update the ticket on Monday.

**Comment by ElLamparto** [comment]
Tested the version of yesterday (8th Nov.). No sounds. It still doesn't work.

**Comment by JFreegman** [comment]
I've tested it on two different 32-bit VM's including Debian Jessie and it works fine. Are you sure it's not an issue with your setup? Can you tell me your toxic version and double check that sounds aren't disabled in your config file? Does the directory `/usr/share/toxic/sounds` exist and have a bunch of .wav files in it?

**Comment by ElLamparto** [comment]
OK, I'll recheck all of that.
I tested the "contact coming online" sound.

Thank you.

**Comment by JFreegman** [comment]
If you have X11 enabled (default) then some sounds won't play if the window is focused. Also, the contact online sound won't play for the first 30 or so seconds after you open toxic. The best way to test if sound is working is to hold the backspace, or /call someone.

**Comment by ElLamparto** [comment]
Thanks for info! I'll test it tonight on two Jessie machines..

**Comment by ElLamparto** [comment]
It works. I was not aware of the 30s. I also find strange, that playing a wave file depends on terminal window being focused or not.

But otherwise it works fine. Thanks.
